---
# tasks file for roles/pma
- name: Install phpmyadmin
  apt: 
    name: "{{ item }}"
    state: present 
  with_items: 
    - php-mbstring
    - php-zip 
    - php-gd 
    - php-json 
    - php-curl

- name: Enable phpenmod
  ansible.builtin.shell: sudo phpenmod mbstring

- name: debconf for pma
  debconf: 
    name: phpmyadmin
    question: 'phpmyadmin/dbconfig-install' 
    value: 'true'
    vtype: 'boolean'

- name: debconf for pma
  debconf: 
    name: phpmyadmin
    question: 'phpmyadmin/app-password-confirm'
    value: '{{mysql_password}}' 
    vtype: 'password'

- name: debconf for pma
  debconf: 
    name: phpmyadmin
    question: 'phpmyadmin/mysql/admin-pass'
    value: '{{mysql_password}}' 
    vtype: 'password'

- name: debconf for pma
  debconf: 
    name: phpmyadmin 
    question: 'phpmyadmin/mysql/app-pass' 
    value: '{{mysql_password}}' 
    vtype: 'password'

- name: debconf for pma
  debconf: 
    name: phpmyadmin
    question: 'phpmyadmin/reconfigure-webserver'
    value: '' 
    vtype: 'multiselect'

- name: Install phpmyadmin
  apt: 
    pkg: phpmyadmin 
    state: present

- name: configure site
  file: 
    path: /var/www/phpmyadmin 
    src: /usr/share/phpmyadmin 
    state: link
 